package com.jackpot.follow_init;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class InformationActivity extends AppCompatActivity {
    TextView license;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_licensing);
        license = (TextView)findViewById(R.id.licenseText);
        license.setText("The following sets forth attribution notices for third party software that may be contained in portions of the Instagram product. We thank the open source community for all of their contributions.\n" +
                "\n" +
                "=====\n" +
                "\n" +
                "The following software may be included in this product:\n" +
                "To-Do-App\n" +
                "\n" +
                "This software contains the following license and notice below:\n" +
                "\n" +
                "Project-wide Gradle settings. \n" +
                " \n" +
                "IDE (e.g. Android Studio) users: \n" +
                "Gradle settings configured through the IDE *will override* \n" +
                "any settings specified in this file. \n" +
                "\n" +
                " \n" +
                "For more details on how to configure your build environment visit \n" +
                "http://www.gradle.org/docs/current/userguide/build_environment.html \n" +
                "\n" +
                " \n" +
                "Specifies the JVM arguments used for the daemon process. \n" +
                "The setting is particularly useful for tweaking memory settings. \n" +
                "Default value: -Xmx10248m -XX:MaxPermSize=256m \n" +
                "org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 \n" +
                "\n" +
                " \n" +
                "When configured, Gradle will run in incubating parallel mode. \n" +
                "This option should only be used with decoupled projects. More details, visit \n" +
                "http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects \n" +
                "org.gradle.parallel=true \n" +
                "\n" +
                "\n" +
                "=====\n" +
                "\n" +
                "The following software may be included in this product:\n" +
                "TimeTableView\n" +
                "\n" +
                "This file is automatically generated by Android Studio. \n" +
                "Do not modify this file -- YOUR CHANGES WILL BE ERASED! \n" +
                " \n" +
                "This file must *NOT* be checked into Version Control Systems, \n" +
                "as it contains information specific to your local configuration. \n" +
                "\n" +
                "Location of the SDK. This is only used by Gradle. \n" +
                "For customization when using a Version Control System, please read the \n" +
                "header note. \n" +
                "\n" +
                "\n" +
                "=====\n" +
                "\n" +
                "The following software may be included in this product:\n" +
                "Google Map API\n" +
                "\n" +
                "This software contains the following license and notice below:\n" +
                "\n" +
                "When you see a page with this notice you are free to use nearly everything on the page in your own creations. \n" +
                "For example, you could quote the text in a book, cut-and-paste sections to your blog, record it as an audiobook\n" +
                "for the visually impaired, or even translate it into Swahili. Really. That's what open content licenses are all about.\n" +
                "We just ask that you give us attribution when you reuse our work.\n" +
                "\n" +
                "Unless required by applicable law or agreed to in writing, software\n" +
                "distributed under the License is distributed on an \"AS IS\" BASIS,\n" +
                "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" +
                "See the License for the specific language governing permissions and\n" +
                "limitations under the License.\n" +
                "\n" +
                "=====\n" +
                "\n" +
                "The following software may be included in this product:\n" +
                "Google places API\n" +
                "\n" +
                "This software contains the following license and notice below:\n" +
                "\n" +
                "Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License,\n" +
                " and code samples are licensed under the Apache 2.0 License. For details, see our Site Policies. \n" +
                "Java is a registered trademark of Oracle and/or its affiliates.\n" +
                "\n" +
                "Unless required by applicable law or agreed to in writing, software\n" +
                "distributed under the License is distributed on an \"AS IS\" BASIS,\n" +
                "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" +
                "See the License for the specific language governing permissions and\n" +
                "limitations under the License.\n" +
                "\n" +
                "=====\n" +
                "\n" +
                "The following software may be included in this product:\n" +
                "ODsey API\n" +
                "\n" +
                "This software contains the following license and notice below:\n" +
                "\n" +
                "Licensed under the Apache License, Version 2.0 (the \"License\");\n" +
                "you may not use this file except in compliance with the License.\n" +
                "You may obtain a copy of the License at\n" +
                "\n" +
                "   http://www.apache.org/licenses/LICENSE-2.0\n" +
                "\n" +
                "Unless required by applicable law or agreed to in writing, software\n" +
                "distributed under the License is distributed on an \"AS IS\" BASIS,\n" +
                "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" +
                "See the License for the specific language governing permissions and\n" +
                "limitations under the License.\n" +
                "\n" +
                "=====");
    }
}